### ISSUE TITLE
Milestone 2 Code Comments

### ISSUE THREAD

**Issue by ahofmann4** [UBC-MDS/dsci-522-group14#63]
Overall your code is well written and formatted, and includes tests as needed!

I however ran into a significant problem running your third command. The first code worked, second code worked.
third code error I think due to my browser version of Chrome not matching the python-chromedriver-binary version I downloaded. I was not notified of this in the dependencies, and was not able to download the version specified in the dependencies either, installed most recent version, and don't think a request to change my Chrome App version on my computer is in order. I think it would be best to remove the chrome-driver package if you can to reduce the dependencies problems I encountered. See below for the error I was unable to overcome:
 
------- output of my terminal running: python src/eda_wine.py --datafile=data/processed/train_set.csv --out=results/
Traceback (most recent call last):
  File "src/eda_wine.py", line 177, in <module>
    main(opt['--datafile'], opt['--out'])
  File "src/eda_wine.py", line 37, in main
    save_plot(target_plot, out, "target")
  File "src/eda_wine.py", line 151, in save_plot
    driver = webdriver.Chrome()
  File "/Users/analisehofmann/Desktop/M2_Marking/dsci-522-group14-0.1.0/dsci-522-group14-0.1.0/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 76, in __init__
    RemoteWebDriver.__init__(
  File "/Users/analisehofmann/Desktop/M2_Marking/dsci-522-group14-0.1.0/dsci-522-group14-0.1.0/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Users/analisehofmann/Desktop/M2_Marking/dsci-522-group14-0.1.0/dsci-522-group14-0.1.0/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Users/analisehofmann/Desktop/M2_Marking/dsci-522-group14-0.1.0/dsci-522-group14-0.1.0/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/analisehofmann/Desktop/M2_Marking/dsci-522-group14-0.1.0/dsci-522-group14-0.1.0/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 88
Current browser version is 86.0.4240.198 with binary path /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

------------

**Comment by vigneshRajakumar** [comment]
Hi @ahofmann4,  thanks for the feedback!

Coincidentally, we came to the exact same conclusion in our Milestone 3 meetings 😄. 

We have a couple of developments that we included in Milestone 3:

1. #56 -> We updated our readme to reflect the Chrome dependency, we will update it again with the version our analysis successfully ran on
2. #59 -> We have an issue in our pipeline to remove the chrome/selenium dependency completely,  if possible.
